language: go

sudo: required

services:
  - docker

go:
  - 1.11.x

before_install:
  - GO111MODULE=on go mod vendor

install:
  - echo "noop"

script:
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)